module.exports = {
    province: function() {
        return [ {
            id: 1,
            cls: "cur",
            count: 0,
            name: "热门",
            city: [ {
                id: 101,
                pid: 1,
                name: "北京",
                cls: "citybtn"
            }, {
                id: 102,
                pid: 1,
                name: "上海",
                cls: "citybtn"
            }, {
                id: 103,
                pid: 1,
                name: "天津",
                cls: "citybtn"
            }, {
                id: 104,
                pid: 1,
                name: "重庆",
                cls: "citybtn"
            }, {
                id: 105,
                pid: 1,
                name: "香港",
                cls: "citybtn"
            }, {
                id: 106,
                pid: 1,
                name: "澳门",
                cls: "citybtn"
            } ]
        }, {
            id: 2,
            cls: "pview",
            count: 0,
            name: "江苏",
            city: [ {
                id: 201,
                pid: 2,
                name: "南京",
                cls: "citybtn"
            }, {
                id: 202,
                pid: 2,
                name: "徐州",
                cls: "citybtn"
            }, {
                id: 203,
                pid: 2,
                name: "连云港",
                cls: "citybtn"
            }, {
                id: 204,
                pid: 2,
                name: "宿迁",
                cls: "citybtn"
            }, {
                id: 205,
                pid: 2,
                name: "淮安",
                cls: "citybtn"
            }, {
                id: 206,
                pid: 2,
                name: "盐城",
                cls: "citybtn"
            }, {
                id: 207,
                pid: 2,
                name: "扬州",
                cls: "citybtn"
            }, {
                id: 208,
                pid: 2,
                name: "泰州",
                cls: "citybtn"
            }, {
                id: 209,
                pid: 2,
                name: "南通",
                cls: "citybtn"
            }, {
                id: 210,
                pid: 2,
                name: "镇江",
                cls: "citybtn"
            }, {
                id: 211,
                pid: 2,
                name: "常州",
                cls: "citybtn"
            }, {
                id: 212,
                pid: 2,
                name: "无锡",
                cls: "citybtn"
            }, {
                id: 213,
                pid: 2,
                name: "苏州",
                cls: "citybtn"
            }, {
                id: 214,
                pid: 2,
                name: "江阴",
                cls: "citybtn"
            }, {
                id: 215,
                pid: 2,
                name: "宜兴",
                cls: "citybtn"
            }, {
                id: 216,
                pid: 2,
                name: "邳州",
                cls: "citybtn"
            }, {
                id: 217,
                pid: 2,
                name: "新沂",
                cls: "citybtn"
            }, {
                id: 218,
                pid: 2,
                name: "金坛",
                cls: "citybtn"
            }, {
                id: 219,
                pid: 2,
                name: "溧阳",
                cls: "citybtn"
            }, {
                id: 220,
                pid: 2,
                name: "常熟",
                cls: "citybtn"
            }, {
                id: 221,
                pid: 2,
                name: "张家港",
                cls: "citybtn"
            }, {
                id: 222,
                pid: 2,
                name: "太仓",
                cls: "citybtn"
            }, {
                id: 223,
                pid: 2,
                name: "昆山",
                cls: "citybtn"
            }, {
                id: 224,
                pid: 2,
                name: "吴江",
                cls: "citybtn"
            }, {
                id: 225,
                pid: 2,
                name: "如皋",
                cls: "citybtn"
            }, {
                id: 226,
                pid: 2,
                name: "海门",
                cls: "citybtn"
            }, {
                id: 227,
                pid: 2,
                name: "启东",
                cls: "citybtn"
            }, {
                id: 228,
                pid: 2,
                name: "大丰",
                cls: "citybtn"
            }, {
                id: 229,
                pid: 2,
                name: "东台",
                cls: "citybtn"
            }, {
                id: 230,
                pid: 2,
                name: "高邮",
                cls: "citybtn"
            }, {
                id: 231,
                pid: 2,
                name: "仪征",
                cls: "citybtn"
            }, {
                id: 232,
                pid: 2,
                name: "扬中",
                cls: "citybtn"
            }, {
                id: 233,
                pid: 2,
                name: "句容",
                cls: "citybtn"
            }, {
                id: 234,
                pid: 2,
                name: "丹阳",
                cls: "citybtn"
            }, {
                id: 235,
                pid: 2,
                name: "兴化",
                cls: "citybtn"
            }, {
                id: 236,
                pid: 2,
                name: "姜堰",
                cls: "citybtn"
            }, {
                id: 237,
                pid: 2,
                name: "泰兴",
                cls: "citybtn"
            }, {
                id: 238,
                pid: 2,
                name: "靖江",
                cls: "citybtn"
            } ]
        }, {
            id: 3,
            cls: "pview",
            count: 0,
            name: "浙江",
            city: [ {
                id: 301,
                pid: 3,
                name: "杭州",
                cls: "citybtn"
            }, {
                id: 302,
                pid: 3,
                name: "宁波",
                cls: "citybtn"
            }, {
                id: 303,
                pid: 3,
                name: "湖州",
                cls: "citybtn"
            }, {
                id: 304,
                pid: 3,
                name: "嘉兴",
                cls: "citybtn"
            }, {
                id: 305,
                pid: 3,
                name: "舟山",
                cls: "citybtn"
            }, {
                id: 306,
                pid: 3,
                name: "绍兴",
                cls: "citybtn"
            }, {
                id: 307,
                pid: 3,
                name: "衢州",
                cls: "citybtn"
            }, {
                id: 308,
                pid: 3,
                name: "金华",
                cls: "citybtn"
            }, {
                id: 309,
                pid: 3,
                name: "台州",
                cls: "citybtn"
            }, {
                id: 310,
                pid: 3,
                name: "温州",
                cls: "citybtn"
            }, {
                id: 311,
                pid: 3,
                name: "丽水",
                cls: "citybtn"
            }, {
                id: 312,
                pid: 3,
                name: "临安",
                cls: "citybtn"
            }, {
                id: 313,
                pid: 3,
                name: "富阳",
                cls: "citybtn"
            }, {
                id: 314,
                pid: 3,
                name: "建德",
                cls: "citybtn"
            }, {
                id: 315,
                pid: 3,
                name: "慈溪",
                cls: "citybtn"
            }, {
                id: 316,
                pid: 3,
                name: "余姚",
                cls: "citybtn"
            }, {
                id: 317,
                pid: 3,
                name: "奉化",
                cls: "citybtn"
            }, {
                id: 318,
                pid: 3,
                name: "平湖",
                cls: "citybtn"
            }, {
                id: 319,
                pid: 3,
                name: "海宁",
                cls: "citybtn"
            }, {
                id: 320,
                pid: 3,
                name: "桐乡",
                cls: "citybtn"
            }, {
                id: 321,
                pid: 3,
                name: "诸暨",
                cls: "citybtn"
            }, {
                id: 322,
                pid: 3,
                name: "上虞",
                cls: "citybtn"
            }, {
                id: 323,
                pid: 3,
                name: "嵊州",
                cls: "citybtn"
            }, {
                id: 324,
                pid: 3,
                name: "江山",
                cls: "citybtn"
            }, {
                id: 325,
                pid: 3,
                name: "兰溪",
                cls: "citybtn"
            }, {
                id: 326,
                pid: 3,
                name: "永康",
                cls: "citybtn"
            }, {
                id: 327,
                pid: 3,
                name: "义乌",
                cls: "citybtn"
            }, {
                id: 328,
                pid: 3,
                name: "东阳",
                cls: "citybtn"
            }, {
                id: 329,
                pid: 3,
                name: "临海",
                cls: "citybtn"
            }, {
                id: 330,
                pid: 3,
                name: "温岭",
                cls: "citybtn"
            }, {
                id: 331,
                pid: 3,
                name: "瑞安",
                cls: "citybtn"
            }, {
                id: 332,
                pid: 3,
                name: "乐清",
                cls: "citybtn"
            }, {
                id: 333,
                pid: 3,
                name: "龙泉",
                cls: "citybtn"
            } ]
        }, {
            id: 4,
            cls: "pview",
            count: 0,
            name: "安徽",
            city: [ {
                id: 401,
                pid: 4,
                name: "合肥",
                cls: "citybtn"
            }, {
                id: 402,
                pid: 4,
                name: "芜湖",
                cls: "citybtn"
            }, {
                id: 403,
                pid: 4,
                name: "蚌埠",
                cls: "citybtn"
            }, {
                id: 404,
                pid: 4,
                name: "淮南",
                cls: "citybtn"
            }, {
                id: 405,
                pid: 4,
                name: "马鞍山",
                cls: "citybtn"
            }, {
                id: 406,
                pid: 4,
                name: "淮北",
                cls: "citybtn"
            }, {
                id: 407,
                pid: 4,
                name: "铜陵",
                cls: "citybtn"
            }, {
                id: 408,
                pid: 4,
                name: "安庆",
                cls: "citybtn"
            }, {
                id: 409,
                pid: 4,
                name: "黄山",
                cls: "citybtn"
            }, {
                id: 410,
                pid: 4,
                name: "阜阳",
                cls: "citybtn"
            }, {
                id: 411,
                pid: 4,
                name: "宿州",
                cls: "citybtn"
            }, {
                id: 412,
                pid: 4,
                name: "滁州",
                cls: "citybtn"
            }, {
                id: 413,
                pid: 4,
                name: "六安",
                cls: "citybtn"
            }, {
                id: 414,
                pid: 4,
                name: "宣城",
                cls: "citybtn"
            }, {
                id: 415,
                pid: 4,
                name: "池州",
                cls: "citybtn"
            }, {
                id: 416,
                pid: 4,
                name: "亳州",
                cls: "citybtn"
            }, {
                id: 417,
                pid: 4,
                name: "巢湖",
                cls: "citybtn"
            }, {
                id: 418,
                pid: 4,
                name: "桐城",
                cls: "citybtn"
            }, {
                id: 419,
                pid: 4,
                name: "界首",
                cls: "citybtn"
            }, {
                id: 420,
                pid: 4,
                name: "天长",
                cls: "citybtn"
            }, {
                id: 421,
                pid: 4,
                name: "明光",
                cls: "citybtn"
            }, {
                id: 422,
                pid: 4,
                name: "宁国",
                cls: "citybtn"
            }, {
                id: 423,
                pid: 4,
                name: "歙县",
                cls: "citybtn"
            } ]
        }, {
            id: 26,
            cls: "pview",
            count: 0,
            name: "海南",
            city: [ {
                id: 2601,
                pid: 26,
                name: "海口市",
                cls: "citybtn"
            }, {
                id: 2602,
                pid: 26,
                name: "三亚市",
                cls: "citybtn"
            }, {
                id: 2603,
                pid: 26,
                name: "文昌市",
                cls: "citybtn"
            }, {
                id: 2604,
                pid: 26,
                name: "琼海市",
                cls: "citybtn"
            }, {
                id: 2605,
                pid: 26,
                name: "万宁市",
                cls: "citybtn"
            }, {
                id: 2606,
                pid: 26,
                name: "东方市",
                cls: "citybtn"
            }, {
                id: 2607,
                pid: 26,
                name: "儋州市",
                cls: "citybtn"
            }, {
                id: 2608,
                pid: 26,
                name: "五指山市",
                cls: "citybtn"
            }, {
                id: 2609,
                pid: 26,
                name: "南沙群岛",
                cls: "citybtn"
            } ]
        }, {
            id: 27,
            cls: "pview",
            count: 0,
            name: "四川",
            city: [ {
                id: 2701,
                pid: 27,
                name: "成都",
                cls: "citybtn"
            }, {
                id: 2702,
                pid: 27,
                name: "广元",
                cls: "citybtn"
            }, {
                id: 2703,
                pid: 27,
                name: "绵阳",
                cls: "citybtn"
            }, {
                id: 2704,
                pid: 27,
                name: "德阳",
                cls: "citybtn"
            }, {
                id: 2705,
                pid: 27,
                name: "南充",
                cls: "citybtn"
            }, {
                id: 2706,
                pid: 27,
                name: "广安",
                cls: "citybtn"
            }, {
                id: 2707,
                pid: 27,
                name: "遂宁",
                cls: "citybtn"
            }, {
                id: 2708,
                pid: 27,
                name: "内江",
                cls: "citybtn"
            }, {
                id: 2709,
                pid: 27,
                name: "乐山",
                cls: "citybtn"
            }, {
                id: 2710,
                pid: 27,
                name: "自贡",
                cls: "citybtn"
            }, {
                id: 2711,
                pid: 27,
                name: "泸州",
                cls: "citybtn"
            }, {
                id: 2712,
                pid: 27,
                name: "宜宾",
                cls: "citybtn"
            }, {
                id: 2713,
                pid: 27,
                name: "攀枝花",
                cls: "citybtn"
            }, {
                id: 2714,
                pid: 27,
                name: "巴中",
                cls: "citybtn"
            }, {
                id: 2715,
                pid: 27,
                name: "达州",
                cls: "citybtn"
            }, {
                id: 2716,
                pid: 27,
                name: "资阳",
                cls: "citybtn"
            }, {
                id: 2717,
                pid: 27,
                name: "眉山",
                cls: "citybtn"
            }, {
                id: 2718,
                pid: 27,
                name: "雅安",
                cls: "citybtn"
            }, {
                id: 2719,
                pid: 27,
                name: "崇州",
                cls: "citybtn"
            }, {
                id: 2720,
                pid: 27,
                name: "邛崃",
                cls: "citybtn"
            }, {
                id: 2721,
                pid: 27,
                name: "都江堰",
                cls: "citybtn"
            }, {
                id: 2722,
                pid: 27,
                name: "彭州",
                cls: "citybtn"
            }, {
                id: 2723,
                pid: 27,
                name: "江油",
                cls: "citybtn"
            }, {
                id: 2724,
                pid: 27,
                name: "什邡",
                cls: "citybtn"
            }, {
                id: 2725,
                pid: 27,
                name: "广汉",
                cls: "citybtn"
            }, {
                id: 2726,
                pid: 27,
                name: "绵竹",
                cls: "citybtn"
            }, {
                id: 2727,
                pid: 27,
                name: "阆中",
                cls: "citybtn"
            }, {
                id: 2728,
                pid: 27,
                name: "华蓥",
                cls: "citybtn"
            }, {
                id: 2729,
                pid: 27,
                name: "峨眉山",
                cls: "citybtn"
            }, {
                id: 2730,
                pid: 27,
                name: "万源",
                cls: "citybtn"
            }, {
                id: 2731,
                pid: 27,
                name: "简阳",
                cls: "citybtn"
            }, {
                id: 2732,
                pid: 27,
                name: "西昌",
                cls: "citybtn"
            } ]
        }, {
            id: 29,
            cls: "pview",
            count: 0,
            name: "云南",
            city: [ {
                id: 2901,
                pid: 29,
                name: "昆明",
                cls: "citybtn"
            }, {
                id: 2902,
                pid: 29,
                name: "曲靖",
                cls: "citybtn"
            }, {
                id: 2903,
                pid: 29,
                name: "玉溪",
                cls: "citybtn"
            }, {
                id: 2904,
                pid: 29,
                name: "丽江",
                cls: "citybtn"
            }, {
                id: 2905,
                pid: 29,
                name: "昭通",
                cls: "citybtn"
            }, {
                id: 2906,
                pid: 29,
                name: "思茅",
                cls: "citybtn"
            }, {
                id: 2907,
                pid: 29,
                name: "临沧",
                cls: "citybtn"
            }, {
                id: 2908,
                pid: 29,
                name: "保山",
                cls: "citybtn"
            }, {
                id: 2909,
                pid: 29,
                name: "安宁",
                cls: "citybtn"
            }, {
                id: 2910,
                pid: 29,
                name: "宣威",
                cls: "citybtn"
            }, {
                id: 2911,
                pid: 29,
                name: "芒市",
                cls: "citybtn"
            }, {
                id: 2912,
                pid: 29,
                name: "瑞丽",
                cls: "citybtn"
            }, {
                id: 2913,
                pid: 29,
                name: "大理",
                cls: "citybtn"
            }, {
                id: 2914,
                pid: 29,
                name: "楚雄",
                cls: "citybtn"
            }, {
                id: 2915,
                pid: 29,
                name: "个旧",
                cls: "citybtn"
            }, {
                id: 2916,
                pid: 29,
                name: "开远",
                cls: "citybtn"
            }, {
                id: 2917,
                pid: 29,
                name: "景洪",
                cls: "citybtn"
            }, {
                id: 2918,
                pid: 29,
                name: "普洱",
                cls: "citybtn"
            }, {
                id: 2919,
                pid: 29,
                name: "腾冲",
                cls: "citybtn"
            }, {
                id: 2920,
                pid: 29,
                name: "西双版纳",
                cls: "citybtn"
            }, {
                id: 2921,
                pid: 29,
                name: "文山",
                cls: "citybtn"
            }, {
                id: 2922,
                pid: 29,
                name: "红河",
                cls: "citybtn"
            }, {
                id: 2923,
                pid: 29,
                name: "德宏",
                cls: "citybtn"
            }, {
                id: 2924,
                pid: 29,
                name: "怒江",
                cls: "citybtn"
            }, {
                id: 2925,
                pid: 29,
                name: "迪庆",
                cls: "citybtn"
            } ]
        }, {
            id: 5,
            cls: "pview",
            count: 0,
            name: "河南",
            city: [ {
                id: 501,
                pid: 5,
                name: "郑州",
                cls: "citybtn"
            }, {
                id: 502,
                pid: 5,
                name: "开封",
                cls: "citybtn"
            }, {
                id: 503,
                pid: 5,
                name: "洛阳",
                cls: "citybtn"
            }, {
                id: 504,
                pid: 5,
                name: "平顶山",
                cls: "citybtn"
            }, {
                id: 505,
                pid: 5,
                name: "安阳",
                cls: "citybtn"
            }, {
                id: 506,
                pid: 5,
                name: "鹤壁",
                cls: "citybtn"
            }, {
                id: 507,
                pid: 5,
                name: "新乡",
                cls: "citybtn"
            }, {
                id: 508,
                pid: 5,
                name: "焦作",
                cls: "citybtn"
            }, {
                id: 509,
                pid: 5,
                name: "濮阳",
                cls: "citybtn"
            }, {
                id: 510,
                pid: 5,
                name: "许昌",
                cls: "citybtn"
            }, {
                id: 511,
                pid: 5,
                name: "漯河",
                cls: "citybtn"
            }, {
                id: 512,
                pid: 5,
                name: "三门峡",
                cls: "citybtn"
            }, {
                id: 513,
                pid: 5,
                name: "南阳",
                cls: "citybtn"
            }, {
                id: 514,
                pid: 5,
                name: "商丘",
                cls: "citybtn"
            }, {
                id: 515,
                pid: 5,
                name: "周口",
                cls: "citybtn"
            }, {
                id: 516,
                pid: 5,
                name: "驻马店",
                cls: "citybtn"
            }, {
                id: 517,
                pid: 5,
                name: "信阳",
                cls: "citybtn"
            }, {
                id: 518,
                pid: 5,
                name: "济源",
                cls: "citybtn"
            }, {
                id: 519,
                pid: 5,
                name: "巩义",
                cls: "citybtn"
            }, {
                id: 520,
                pid: 5,
                name: "邓州",
                cls: "citybtn"
            }, {
                id: 521,
                pid: 5,
                name: "永城",
                cls: "citybtn"
            }, {
                id: 522,
                pid: 5,
                name: "汝州",
                cls: "citybtn"
            }, {
                id: 523,
                pid: 5,
                name: "荥阳",
                cls: "citybtn"
            }, {
                id: 524,
                pid: 5,
                name: "新郑",
                cls: "citybtn"
            }, {
                id: 525,
                pid: 5,
                name: "登封",
                cls: "citybtn"
            }, {
                id: 526,
                pid: 5,
                name: "新密",
                cls: "citybtn"
            }, {
                id: 527,
                pid: 5,
                name: "偃师",
                cls: "citybtn"
            }, {
                id: 528,
                pid: 5,
                name: "孟州",
                cls: "citybtn"
            }, {
                id: 529,
                pid: 5,
                name: "沁阳",
                cls: "citybtn"
            }, {
                id: 530,
                pid: 5,
                name: "卫辉",
                cls: "citybtn"
            }, {
                id: 531,
                pid: 5,
                name: "辉县",
                cls: "citybtn"
            }, {
                id: 532,
                pid: 5,
                name: "林州",
                cls: "citybtn"
            }, {
                id: 533,
                pid: 5,
                name: "禹州",
                cls: "citybtn"
            }, {
                id: 534,
                pid: 5,
                name: "长葛",
                cls: "citybtn"
            }, {
                id: 535,
                pid: 5,
                name: "舞钢",
                cls: "citybtn"
            }, {
                id: 536,
                pid: 5,
                name: "义马",
                cls: "citybtn"
            }, {
                id: 537,
                pid: 5,
                name: "灵宝",
                cls: "citybtn"
            }, {
                id: 538,
                pid: 5,
                name: "项城",
                cls: "citybtn"
            } ]
        }, {
            id: 6,
            cls: "pview",
            count: 0,
            name: "山东",
            city: [ {
                id: 601,
                pid: 6,
                name: "济南",
                cls: "citybtn"
            }, {
                id: 602,
                pid: 6,
                name: "青岛",
                cls: "citybtn"
            }, {
                id: 603,
                pid: 6,
                name: "聊城",
                cls: "citybtn"
            }, {
                id: 604,
                pid: 6,
                name: "德州",
                cls: "citybtn"
            }, {
                id: 605,
                pid: 6,
                name: "东营",
                cls: "citybtn"
            }, {
                id: 606,
                pid: 6,
                name: "淄博",
                cls: "citybtn"
            }, {
                id: 607,
                pid: 6,
                name: "潍坊",
                cls: "citybtn"
            }, {
                id: 608,
                pid: 6,
                name: "烟台",
                cls: "citybtn"
            }, {
                id: 609,
                pid: 6,
                name: "威海",
                cls: "citybtn"
            }, {
                id: 610,
                pid: 6,
                name: "日照",
                cls: "citybtn"
            }, {
                id: 611,
                pid: 6,
                name: "临沂",
                cls: "citybtn"
            }, {
                id: 612,
                pid: 6,
                name: "枣庄",
                cls: "citybtn"
            }, {
                id: 613,
                pid: 6,
                name: "济宁",
                cls: "citybtn"
            }, {
                id: 614,
                pid: 6,
                name: "泰安",
                cls: "citybtn"
            }, {
                id: 615,
                pid: 6,
                name: "莱芜",
                cls: "citybtn"
            }, {
                id: 616,
                pid: 6,
                name: "滨州",
                cls: "citybtn"
            }, {
                id: 617,
                pid: 6,
                name: "菏泽",
                cls: "citybtn"
            }, {
                id: 618,
                pid: 6,
                name: "章丘",
                cls: "citybtn"
            }, {
                id: 619,
                pid: 6,
                name: "胶州",
                cls: "citybtn"
            }, {
                id: 620,
                pid: 6,
                name: "胶南",
                cls: "citybtn"
            }, {
                id: 621,
                pid: 6,
                name: "即墨",
                cls: "citybtn"
            }, {
                id: 622,
                pid: 6,
                name: "平度",
                cls: "citybtn"
            }, {
                id: 623,
                pid: 6,
                name: "莱西",
                cls: "citybtn"
            }, {
                id: 624,
                pid: 6,
                name: "临清",
                cls: "citybtn"
            }, {
                id: 625,
                pid: 6,
                name: "乐陵",
                cls: "citybtn"
            }, {
                id: 626,
                pid: 6,
                name: "禹城",
                cls: "citybtn"
            }, {
                id: 627,
                pid: 6,
                name: "安丘",
                cls: "citybtn"
            }, {
                id: 628,
                pid: 6,
                name: "昌邑",
                cls: "citybtn"
            }, {
                id: 629,
                pid: 6,
                name: "高密",
                cls: "citybtn"
            }, {
                id: 630,
                pid: 6,
                name: "青州",
                cls: "citybtn"
            }, {
                id: 631,
                pid: 6,
                name: "诸城",
                cls: "citybtn"
            }, {
                id: 632,
                pid: 6,
                name: "寿光",
                cls: "citybtn"
            }, {
                id: 633,
                pid: 6,
                name: "栖霞",
                cls: "citybtn"
            }, {
                id: 634,
                pid: 6,
                name: "海阳",
                cls: "citybtn"
            }, {
                id: 635,
                pid: 6,
                name: "龙口",
                cls: "citybtn"
            }, {
                id: 636,
                pid: 6,
                name: "莱阳",
                cls: "citybtn"
            }, {
                id: 637,
                pid: 6,
                name: "莱州",
                cls: "citybtn"
            }, {
                id: 638,
                pid: 6,
                name: "蓬莱",
                cls: "citybtn"
            }, {
                id: 639,
                pid: 6,
                name: "招远",
                cls: "citybtn"
            }, {
                id: 640,
                pid: 6,
                name: "文登",
                cls: "citybtn"
            }, {
                id: 641,
                pid: 6,
                name: "荣成",
                cls: "citybtn"
            }, {
                id: 642,
                pid: 6,
                name: "乳山",
                cls: "citybtn"
            }, {
                id: 643,
                pid: 6,
                name: "滕州",
                cls: "citybtn"
            }, {
                id: 644,
                pid: 6,
                name: "曲阜",
                cls: "citybtn"
            }, {
                id: 645,
                pid: 6,
                name: "兖州",
                cls: "citybtn"
            }, {
                id: 646,
                pid: 6,
                name: "邹城",
                cls: "citybtn"
            }, {
                id: 647,
                pid: 6,
                name: "新泰",
                cls: "citybtn"
            }, {
                id: 648,
                pid: 6,
                name: "肥城",
                cls: "citybtn"
            } ]
        }, {
            id: 7,
            cls: "pview",
            count: 0,
            name: "河北",
            city: [ {
                id: 701,
                pid: 7,
                name: "石家庄",
                cls: "citybtn"
            }, {
                id: 702,
                pid: 7,
                name: "邯郸",
                cls: "citybtn"
            }, {
                id: 703,
                pid: 7,
                name: "唐山",
                cls: "citybtn"
            }, {
                id: 704,
                pid: 7,
                name: "保定",
                cls: "citybtn"
            }, {
                id: 705,
                pid: 7,
                name: "秦皇岛",
                cls: "citybtn"
            }, {
                id: 706,
                pid: 7,
                name: "邢台",
                cls: "citybtn"
            }, {
                id: 707,
                pid: 7,
                name: "张家口",
                cls: "citybtn"
            }, {
                id: 708,
                pid: 7,
                name: "承德",
                cls: "citybtn"
            }, {
                id: 709,
                pid: 7,
                name: "沧州",
                cls: "citybtn"
            }, {
                id: 710,
                pid: 7,
                name: "廊坊",
                cls: "citybtn"
            }, {
                id: 711,
                pid: 7,
                name: "衡水",
                cls: "citybtn"
            }, {
                id: 712,
                pid: 7,
                name: "辛集",
                cls: "citybtn"
            }, {
                id: 713,
                pid: 7,
                name: "藁城",
                cls: "citybtn"
            }, {
                id: 714,
                pid: 7,
                name: "晋州",
                cls: "citybtn"
            }, {
                id: 715,
                pid: 7,
                name: "新乐",
                cls: "citybtn"
            }, {
                id: 716,
                pid: 7,
                name: "鹿泉",
                cls: "citybtn"
            }, {
                id: 717,
                pid: 7,
                name: "遵化",
                cls: "citybtn"
            }, {
                id: 718,
                pid: 7,
                name: "迁安",
                cls: "citybtn"
            }, {
                id: 719,
                pid: 7,
                name: "霸州",
                cls: "citybtn"
            }, {
                id: 720,
                pid: 7,
                name: "三河",
                cls: "citybtn"
            }, {
                id: 721,
                pid: 7,
                name: "定州",
                cls: "citybtn"
            }, {
                id: 722,
                pid: 7,
                name: "涿州",
                cls: "citybtn"
            }, {
                id: 723,
                pid: 7,
                name: "安国",
                cls: "citybtn"
            }, {
                id: 724,
                pid: 7,
                name: "高碑店",
                cls: "citybtn"
            }, {
                id: 725,
                pid: 7,
                name: "泊头",
                cls: "citybtn"
            }, {
                id: 726,
                pid: 7,
                name: "任丘",
                cls: "citybtn"
            }, {
                id: 727,
                pid: 7,
                name: "黄骅",
                cls: "citybtn"
            }, {
                id: 728,
                pid: 7,
                name: "河间",
                cls: "citybtn"
            }, {
                id: 729,
                pid: 7,
                name: "冀州",
                cls: "citybtn"
            }, {
                id: 730,
                pid: 7,
                name: "深州",
                cls: "citybtn"
            }, {
                id: 731,
                pid: 7,
                name: "南宫",
                cls: "citybtn"
            }, {
                id: 732,
                pid: 7,
                name: "沙河",
                cls: "citybtn"
            }, {
                id: 733,
                pid: 7,
                name: "武安",
                cls: "citybtn"
            } ]
        }, {
            id: 17,
            cls: "pview",
            count: 0,
            name: "陕西",
            city: [ {
                id: 1701,
                pid: 17,
                name: "西安",
                cls: "citybtn"
            }, {
                id: 1702,
                pid: 17,
                name: "延安",
                cls: "citybtn"
            }, {
                id: 1703,
                pid: 17,
                name: "铜川",
                cls: "citybtn"
            }, {
                id: 1704,
                pid: 17,
                name: "渭南",
                cls: "citybtn"
            }, {
                id: 1705,
                pid: 17,
                name: "咸阳",
                cls: "citybtn"
            }, {
                id: 1706,
                pid: 17,
                name: "宝鸡",
                cls: "citybtn"
            }, {
                id: 1707,
                pid: 17,
                name: "汉中",
                cls: "citybtn"
            }, {
                id: 1708,
                pid: 17,
                name: "榆林",
                cls: "citybtn"
            }, {
                id: 1709,
                pid: 17,
                name: "商洛",
                cls: "citybtn"
            }, {
                id: 1710,
                pid: 17,
                name: "安康",
                cls: "citybtn"
            }, {
                id: 1711,
                pid: 17,
                name: "韩城",
                cls: "citybtn"
            }, {
                id: 1712,
                pid: 17,
                name: "华阴",
                cls: "citybtn"
            }, {
                id: 1713,
                pid: 17,
                name: "兴平",
                cls: "citybtn"
            }, {
                id: 1714,
                pid: 17,
                name: "杨凌",
                cls: "citybtn"
            }, {
                id: 1715,
                pid: 17,
                name: "乾县",
                cls: "citybtn"
            }, {
                id: 1716,
                pid: 17,
                name: "潼关",
                cls: "citybtn"
            }, {
                id: 1717,
                pid: 17,
                name: "洛川",
                cls: "citybtn"
            }, {
                id: 1718,
                pid: 17,
                name: "神木",
                cls: "citybtn"
            }, {
                id: 1719,
                pid: 17,
                name: "米脂",
                cls: "citybtn"
            }, {
                id: 1720,
                pid: 17,
                name: "靖边",
                cls: "citybtn"
            } ]
        }, {
            id: 18,
            cls: "pview",
            count: 0,
            name: "山西",
            city: [ {
                id: 1801,
                pid: 18,
                name: "太原",
                cls: "citybtn"
            }, {
                id: 1802,
                pid: 18,
                name: "大同",
                cls: "citybtn"
            }, {
                id: 1803,
                pid: 18,
                name: "朔州",
                cls: "citybtn"
            }, {
                id: 1804,
                pid: 18,
                name: "阳泉",
                cls: "citybtn"
            }, {
                id: 1805,
                pid: 18,
                name: "长治",
                cls: "citybtn"
            }, {
                id: 1806,
                pid: 18,
                name: "晋城",
                cls: "citybtn"
            }, {
                id: 1807,
                pid: 18,
                name: "忻州",
                cls: "citybtn"
            }, {
                id: 1808,
                pid: 18,
                name: "吕梁",
                cls: "citybtn"
            }, {
                id: 1809,
                pid: 18,
                name: "晋中",
                cls: "citybtn"
            }, {
                id: 1810,
                pid: 18,
                name: "临汾",
                cls: "citybtn"
            }, {
                id: 1811,
                pid: 18,
                name: "运城",
                cls: "citybtn"
            }, {
                id: 1812,
                pid: 18,
                name: "古交",
                cls: "citybtn"
            }, {
                id: 1813,
                pid: 18,
                name: "潞城",
                cls: "citybtn"
            }, {
                id: 1814,
                pid: 18,
                name: "高平",
                cls: "citybtn"
            }, {
                id: 1815,
                pid: 18,
                name: "原平",
                cls: "citybtn"
            }, {
                id: 1816,
                pid: 18,
                name: "孝义",
                cls: "citybtn"
            }, {
                id: 1817,
                pid: 18,
                name: "汾阳",
                cls: "citybtn"
            }, {
                id: 1818,
                pid: 18,
                name: "介休",
                cls: "citybtn"
            }, {
                id: 1819,
                pid: 18,
                name: "侯马",
                cls: "citybtn"
            }, {
                id: 1820,
                pid: 18,
                name: "霍州",
                cls: "citybtn"
            }, {
                id: 1821,
                pid: 18,
                name: "永济",
                cls: "citybtn"
            }, {
                id: 1822,
                pid: 18,
                name: "河津",
                cls: "citybtn"
            }, {
                id: 1823,
                pid: 18,
                name: "祁县",
                cls: "citybtn"
            }, {
                id: 1824,
                pid: 18,
                name: "浑源",
                cls: "citybtn"
            }, {
                id: 1825,
                pid: 18,
                name: "洪洞",
                cls: "citybtn"
            }, {
                id: 1826,
                pid: 18,
                name: "平遥",
                cls: "citybtn"
            }, {
                id: 1827,
                pid: 18,
                name: "五台",
                cls: "citybtn"
            } ]
        }, {
            id: 19,
            cls: "pview",
            count: 0,
            name: "湖北",
            city: [ {
                id: 1901,
                pid: 19,
                name: "武汉",
                cls: "citybtn"
            }, {
                id: 1902,
                pid: 19,
                name: "十堰",
                cls: "citybtn"
            }, {
                id: 1903,
                pid: 19,
                name: "襄樊",
                cls: "citybtn"
            }, {
                id: 1904,
                pid: 19,
                name: "荆门",
                cls: "citybtn"
            }, {
                id: 1905,
                pid: 19,
                name: "孝感",
                cls: "citybtn"
            }, {
                id: 1906,
                pid: 19,
                name: "黄冈",
                cls: "citybtn"
            }, {
                id: 1907,
                pid: 19,
                name: "鄂州",
                cls: "citybtn"
            }, {
                id: 1908,
                pid: 19,
                name: "黄石",
                cls: "citybtn"
            }, {
                id: 1909,
                pid: 19,
                name: "咸宁",
                cls: "citybtn"
            }, {
                id: 1910,
                pid: 19,
                name: "荆州",
                cls: "citybtn"
            }, {
                id: 1911,
                pid: 19,
                name: "宜昌",
                cls: "citybtn"
            }, {
                id: 1912,
                pid: 19,
                name: "随州",
                cls: "citybtn"
            }, {
                id: 1913,
                pid: 19,
                name: "仙桃",
                cls: "citybtn"
            }, {
                id: 1914,
                pid: 19,
                name: "天门",
                cls: "citybtn"
            }, {
                id: 1915,
                pid: 19,
                name: "潜江",
                cls: "citybtn"
            }, {
                id: 1916,
                pid: 19,
                name: "丹江口",
                cls: "citybtn"
            }, {
                id: 1917,
                pid: 19,
                name: "老河口",
                cls: "citybtn"
            }, {
                id: 1918,
                pid: 19,
                name: "枣阳",
                cls: "citybtn"
            }, {
                id: 1919,
                pid: 19,
                name: "宜城",
                cls: "citybtn"
            }, {
                id: 1920,
                pid: 19,
                name: "钟祥",
                cls: "citybtn"
            }, {
                id: 1921,
                pid: 19,
                name: "汉川",
                cls: "citybtn"
            }, {
                id: 1922,
                pid: 19,
                name: "应城",
                cls: "citybtn"
            }, {
                id: 1923,
                pid: 19,
                name: "安陆",
                cls: "citybtn"
            }, {
                id: 1924,
                pid: 19,
                name: "广水",
                cls: "citybtn"
            }, {
                id: 1925,
                pid: 19,
                name: "麻城",
                cls: "citybtn"
            }, {
                id: 1926,
                pid: 19,
                name: "武穴",
                cls: "citybtn"
            }, {
                id: 1927,
                pid: 19,
                name: "大冶",
                cls: "citybtn"
            }, {
                id: 1928,
                pid: 19,
                name: "赤壁",
                cls: "citybtn"
            }, {
                id: 1929,
                pid: 19,
                name: "石首",
                cls: "citybtn"
            }, {
                id: 1930,
                pid: 19,
                name: "洪湖",
                cls: "citybtn"
            }, {
                id: 1931,
                pid: 19,
                name: "松滋",
                cls: "citybtn"
            }, {
                id: 1932,
                pid: 19,
                name: "宜都",
                cls: "citybtn"
            }, {
                id: 1933,
                pid: 19,
                name: "枝江",
                cls: "citybtn"
            }, {
                id: 1934,
                pid: 19,
                name: "当阳",
                cls: "citybtn"
            }, {
                id: 1935,
                pid: 19,
                name: "恩施",
                cls: "citybtn"
            }, {
                id: 1936,
                pid: 19,
                name: "利川",
                cls: "citybtn"
            } ]
        }, {
            id: 20,
            cls: "pview",
            count: 0,
            name: "湖南",
            city: [ {
                id: 2001,
                pid: 20,
                name: "长沙",
                cls: "citybtn"
            }, {
                id: 2002,
                pid: 20,
                name: "衡阳",
                cls: "citybtn"
            }, {
                id: 2003,
                pid: 20,
                name: "张家界",
                cls: "citybtn"
            }, {
                id: 2004,
                pid: 20,
                name: "常德",
                cls: "citybtn"
            }, {
                id: 2005,
                pid: 20,
                name: "益阳",
                cls: "citybtn"
            }, {
                id: 2006,
                pid: 20,
                name: "岳阳",
                cls: "citybtn"
            }, {
                id: 2007,
                pid: 20,
                name: "株洲",
                cls: "citybtn"
            }, {
                id: 2008,
                pid: 20,
                name: "湘潭",
                cls: "citybtn"
            }, {
                id: 2009,
                pid: 20,
                name: "郴州",
                cls: "citybtn"
            }, {
                id: 2010,
                pid: 20,
                name: "永州",
                cls: "citybtn"
            }, {
                id: 2011,
                pid: 20,
                name: "邵阳",
                cls: "citybtn"
            }, {
                id: 2012,
                pid: 20,
                name: "怀化",
                cls: "citybtn"
            }, {
                id: 2013,
                pid: 20,
                name: "娄底",
                cls: "citybtn"
            }, {
                id: 2014,
                pid: 20,
                name: "耒阳",
                cls: "citybtn"
            }, {
                id: 2015,
                pid: 20,
                name: "常宁",
                cls: "citybtn"
            }, {
                id: 2016,
                pid: 20,
                name: "浏阳",
                cls: "citybtn"
            }, {
                id: 2017,
                pid: 20,
                name: "津市",
                cls: "citybtn"
            }, {
                id: 2018,
                pid: 20,
                name: "沅江",
                cls: "citybtn"
            }, {
                id: 2019,
                pid: 20,
                name: "汨罗",
                cls: "citybtn"
            }, {
                id: 2020,
                pid: 20,
                name: "临湘",
                cls: "citybtn"
            }, {
                id: 2021,
                pid: 20,
                name: "醴陵",
                cls: "citybtn"
            }, {
                id: 2022,
                pid: 20,
                name: "湘乡",
                cls: "citybtn"
            }, {
                id: 2023,
                pid: 20,
                name: "韶山",
                cls: "citybtn"
            }, {
                id: 2024,
                pid: 20,
                name: "资兴",
                cls: "citybtn"
            }, {
                id: 2025,
                pid: 20,
                name: "武冈",
                cls: "citybtn"
            }, {
                id: 2026,
                pid: 20,
                name: "洪江",
                cls: "citybtn"
            }, {
                id: 2027,
                pid: 20,
                name: "冷水江",
                cls: "citybtn"
            }, {
                id: 2028,
                pid: 20,
                name: "涟源",
                cls: "citybtn"
            }, {
                id: 2029,
                pid: 20,
                name: "吉首",
                cls: "citybtn"
            } ]
        }, {
            id: 21,
            cls: "pview",
            count: 0,
            name: "江西",
            city: [ {
                id: 2101,
                pid: 21,
                name: "南昌",
                cls: "citybtn"
            }, {
                id: 2102,
                pid: 21,
                name: "九江",
                cls: "citybtn"
            }, {
                id: 2103,
                pid: 21,
                name: "景德镇",
                cls: "citybtn"
            }, {
                id: 2104,
                pid: 21,
                name: "鹰潭",
                cls: "citybtn"
            }, {
                id: 2105,
                pid: 21,
                name: "新余",
                cls: "citybtn"
            }, {
                id: 2106,
                pid: 21,
                name: "萍乡",
                cls: "citybtn"
            }, {
                id: 2107,
                pid: 21,
                name: "赣州",
                cls: "citybtn"
            }, {
                id: 2108,
                pid: 21,
                name: "上饶",
                cls: "citybtn"
            }, {
                id: 2109,
                pid: 21,
                name: "抚州",
                cls: "citybtn"
            }, {
                id: 2110,
                pid: 21,
                name: "宜春",
                cls: "citybtn"
            }, {
                id: 2111,
                pid: 21,
                name: "吉安",
                cls: "citybtn"
            }, {
                id: 2112,
                pid: 21,
                name: "瑞昌",
                cls: "citybtn"
            }, {
                id: 2113,
                pid: 21,
                name: "乐平",
                cls: "citybtn"
            }, {
                id: 2114,
                pid: 21,
                name: "瑞金",
                cls: "citybtn"
            }, {
                id: 2115,
                pid: 21,
                name: "南康",
                cls: "citybtn"
            }, {
                id: 2116,
                pid: 21,
                name: "德兴",
                cls: "citybtn"
            }, {
                id: 2117,
                pid: 21,
                name: "丰城",
                cls: "citybtn"
            }, {
                id: 2118,
                pid: 21,
                name: "樟树",
                cls: "citybtn"
            }, {
                id: 2119,
                pid: 21,
                name: "高安",
                cls: "citybtn"
            }, {
                id: 2120,
                pid: 21,
                name: "井冈山",
                cls: "citybtn"
            }, {
                id: 2121,
                pid: 21,
                name: "贵溪",
                cls: "citybtn"
            } ]
        }, {
            id: 8,
            cls: "pview",
            count: 0,
            name: "黑龙江",
            city: [ {
                id: 801,
                pid: 8,
                name: "哈尔滨",
                cls: "citybtn"
            }, {
                id: 802,
                pid: 8,
                name: "齐齐哈尔",
                cls: "citybtn"
            }, {
                id: 803,
                pid: 8,
                name: "黑河",
                cls: "citybtn"
            }, {
                id: 804,
                pid: 8,
                name: "大庆",
                cls: "citybtn"
            }, {
                id: 805,
                pid: 8,
                name: "伊春",
                cls: "citybtn"
            }, {
                id: 806,
                pid: 8,
                name: "鹤岗",
                cls: "citybtn"
            }, {
                id: 807,
                pid: 8,
                name: "佳木斯",
                cls: "citybtn"
            }, {
                id: 808,
                pid: 8,
                name: "双鸭山",
                cls: "citybtn"
            }, {
                id: 809,
                pid: 8,
                name: "七台河",
                cls: "citybtn"
            }, {
                id: 810,
                pid: 8,
                name: "鸡西",
                cls: "citybtn"
            }, {
                id: 811,
                pid: 8,
                name: "牡丹江",
                cls: "citybtn"
            }, {
                id: 812,
                pid: 8,
                name: "绥化",
                cls: "citybtn"
            }, {
                id: 813,
                pid: 8,
                name: "双城",
                cls: "citybtn"
            }, {
                id: 814,
                pid: 8,
                name: "尚志",
                cls: "citybtn"
            }, {
                id: 815,
                pid: 8,
                name: "五常",
                cls: "citybtn"
            }, {
                id: 816,
                pid: 8,
                name: "阿城",
                cls: "citybtn"
            }, {
                id: 817,
                pid: 8,
                name: "讷河",
                cls: "citybtn"
            }, {
                id: 818,
                pid: 8,
                name: "北安",
                cls: "citybtn"
            }, {
                id: 819,
                pid: 8,
                name: "五大连池",
                cls: "citybtn"
            }, {
                id: 820,
                pid: 8,
                name: "铁力",
                cls: "citybtn"
            }, {
                id: 821,
                pid: 8,
                name: "同江",
                cls: "citybtn"
            }, {
                id: 822,
                pid: 8,
                name: "富锦",
                cls: "citybtn"
            }, {
                id: 823,
                pid: 8,
                name: "虎林",
                cls: "citybtn"
            }, {
                id: 824,
                pid: 8,
                name: "密山",
                cls: "citybtn"
            }, {
                id: 825,
                pid: 8,
                name: "绥芬河",
                cls: "citybtn"
            }, {
                id: 826,
                pid: 8,
                name: "海林",
                cls: "citybtn"
            }, {
                id: 827,
                pid: 8,
                name: "宁安",
                cls: "citybtn"
            }, {
                id: 828,
                pid: 8,
                name: "安达",
                cls: "citybtn"
            }, {
                id: 829,
                pid: 8,
                name: "肇东",
                cls: "citybtn"
            }, {
                id: 830,
                pid: 8,
                name: "海伦",
                cls: "citybtn"
            }, {
                id: 831,
                pid: 8,
                name: "大兴安岭",
                cls: "citybtn"
            } ]
        }, {
            id: 9,
            cls: "pview",
            count: 0,
            name: "吉林",
            city: [ {
                id: 901,
                pid: 9,
                name: "长春",
                cls: "citybtn"
            }, {
                id: 902,
                pid: 9,
                name: "吉林市",
                cls: "citybtn"
            }, {
                id: 903,
                pid: 9,
                name: "白城",
                cls: "citybtn"
            }, {
                id: 904,
                pid: 9,
                name: "松原",
                cls: "citybtn"
            }, {
                id: 905,
                pid: 9,
                name: "四平",
                cls: "citybtn"
            }, {
                id: 906,
                pid: 9,
                name: "辽源",
                cls: "citybtn"
            }, {
                id: 907,
                pid: 9,
                name: "通化",
                cls: "citybtn"
            }, {
                id: 908,
                pid: 9,
                name: "白山",
                cls: "citybtn"
            }, {
                id: 909,
                pid: 9,
                name: "德惠",
                cls: "citybtn"
            }, {
                id: 910,
                pid: 9,
                name: "九台",
                cls: "citybtn"
            }, {
                id: 911,
                pid: 9,
                name: "榆树",
                cls: "citybtn"
            }, {
                id: 912,
                pid: 9,
                name: "磐石",
                cls: "citybtn"
            }, {
                id: 913,
                pid: 9,
                name: "蛟河",
                cls: "citybtn"
            }, {
                id: 914,
                pid: 9,
                name: "桦甸",
                cls: "citybtn"
            }, {
                id: 915,
                pid: 9,
                name: "舒兰",
                cls: "citybtn"
            }, {
                id: 916,
                pid: 9,
                name: "洮南",
                cls: "citybtn"
            }, {
                id: 917,
                pid: 9,
                name: "大安",
                cls: "citybtn"
            }, {
                id: 918,
                pid: 9,
                name: "双辽",
                cls: "citybtn"
            }, {
                id: 919,
                pid: 9,
                name: "公主岭",
                cls: "citybtn"
            }, {
                id: 920,
                pid: 9,
                name: "梅河口",
                cls: "citybtn"
            }, {
                id: 921,
                pid: 9,
                name: "集安",
                cls: "citybtn"
            }, {
                id: 922,
                pid: 9,
                name: "临江",
                cls: "citybtn"
            }, {
                id: 923,
                pid: 9,
                name: "延吉",
                cls: "citybtn"
            }, {
                id: 924,
                pid: 9,
                name: "图们",
                cls: "citybtn"
            }, {
                id: 925,
                pid: 9,
                name: "敦化",
                cls: "citybtn"
            }, {
                id: 926,
                pid: 9,
                name: "珲春",
                cls: "citybtn"
            }, {
                id: 927,
                pid: 9,
                name: "龙井",
                cls: "citybtn"
            }, {
                id: 928,
                pid: 9,
                name: "和龙",
                cls: "citybtn"
            } ]
        }, {
            id: 10,
            cls: "pview",
            count: 0,
            name: "辽宁",
            city: [ {
                id: 1001,
                pid: 10,
                name: "沈阳",
                cls: "citybtn"
            }, {
                id: 1002,
                pid: 10,
                name: "大连",
                cls: "citybtn"
            }, {
                id: 1003,
                pid: 10,
                name: "朝阳",
                cls: "citybtn"
            }, {
                id: 1004,
                pid: 10,
                name: "阜新",
                cls: "citybtn"
            }, {
                id: 1005,
                pid: 10,
                name: "铁岭",
                cls: "citybtn"
            }, {
                id: 1006,
                pid: 10,
                name: "抚顺",
                cls: "citybtn"
            }, {
                id: 1007,
                pid: 10,
                name: "本溪",
                cls: "citybtn"
            }, {
                id: 1008,
                pid: 10,
                name: "辽阳",
                cls: "citybtn"
            }, {
                id: 1009,
                pid: 10,
                name: "鞍山",
                cls: "citybtn"
            }, {
                id: 1010,
                pid: 10,
                name: "丹东",
                cls: "citybtn"
            }, {
                id: 1011,
                pid: 10,
                name: "营口",
                cls: "citybtn"
            }, {
                id: 1012,
                pid: 10,
                name: "盘锦",
                cls: "citybtn"
            }, {
                id: 1013,
                pid: 10,
                name: "锦州",
                cls: "citybtn"
            }, {
                id: 1014,
                pid: 10,
                name: "葫芦岛",
                cls: "citybtn"
            }, {
                id: 1015,
                pid: 10,
                name: "新民",
                cls: "citybtn"
            }, {
                id: 1016,
                pid: 10,
                name: "瓦房店",
                cls: "citybtn"
            }, {
                id: 1017,
                pid: 10,
                name: "普兰店",
                cls: "citybtn"
            }, {
                id: 1018,
                pid: 10,
                name: "庄河",
                cls: "citybtn"
            }, {
                id: 1019,
                pid: 10,
                name: "北票",
                cls: "citybtn"
            }, {
                id: 1020,
                pid: 10,
                name: "凌源",
                cls: "citybtn"
            }, {
                id: 1021,
                pid: 10,
                name: "调兵山",
                cls: "citybtn"
            }, {
                id: 1022,
                pid: 10,
                name: "开原",
                cls: "citybtn"
            }, {
                id: 1023,
                pid: 10,
                name: "灯塔",
                cls: "citybtn"
            }, {
                id: 1024,
                pid: 10,
                name: "海城",
                cls: "citybtn"
            }, {
                id: 1025,
                pid: 10,
                name: "凤城",
                cls: "citybtn"
            }, {
                id: 1026,
                pid: 10,
                name: "东港",
                cls: "citybtn"
            }, {
                id: 1027,
                pid: 10,
                name: "大石桥",
                cls: "citybtn"
            }, {
                id: 1028,
                pid: 10,
                name: "盖州",
                cls: "citybtn"
            }, {
                id: 1029,
                pid: 10,
                name: "凌海",
                cls: "citybtn"
            }, {
                id: 1030,
                pid: 10,
                name: "北宁",
                cls: "citybtn"
            }, {
                id: 1031,
                pid: 10,
                name: "兴城",
                cls: "citybtn"
            } ]
        }, {
            id: 11,
            cls: "pview",
            count: 0,
            name: "内蒙古",
            city: [ {
                id: 1101,
                pid: 11,
                name: "呼和浩特",
                cls: "citybtn"
            }, {
                id: 1102,
                pid: 11,
                name: "包头",
                cls: "citybtn"
            }, {
                id: 1103,
                pid: 11,
                name: "乌海",
                cls: "citybtn"
            }, {
                id: 1104,
                pid: 11,
                name: "赤峰",
                cls: "citybtn"
            }, {
                id: 1105,
                pid: 11,
                name: "呼伦贝尔",
                cls: "citybtn"
            }, {
                id: 1106,
                pid: 11,
                name: "通辽",
                cls: "citybtn"
            }, {
                id: 1107,
                pid: 11,
                name: "乌兰察布",
                cls: "citybtn"
            }, {
                id: 1108,
                pid: 11,
                name: "鄂尔多斯",
                cls: "citybtn"
            }, {
                id: 1109,
                pid: 11,
                name: "巴彦淖尔",
                cls: "citybtn"
            }, {
                id: 1110,
                pid: 11,
                name: "满洲里",
                cls: "citybtn"
            }, {
                id: 1111,
                pid: 11,
                name: "扎兰屯",
                cls: "citybtn"
            }, {
                id: 1112,
                pid: 11,
                name: "牙克石",
                cls: "citybtn"
            }, {
                id: 1113,
                pid: 11,
                name: "根河",
                cls: "citybtn"
            }, {
                id: 1114,
                pid: 11,
                name: "额尔古纳",
                cls: "citybtn"
            }, {
                id: 1115,
                pid: 11,
                name: "乌兰浩特",
                cls: "citybtn"
            }, {
                id: 1116,
                pid: 11,
                name: "阿尔山",
                cls: "citybtn"
            }, {
                id: 1117,
                pid: 11,
                name: "霍林郭勒",
                cls: "citybtn"
            }, {
                id: 1118,
                pid: 11,
                name: "锡林浩特",
                cls: "citybtn"
            }, {
                id: 1119,
                pid: 11,
                name: "二连浩特",
                cls: "citybtn"
            }, {
                id: 1120,
                pid: 11,
                name: "丰镇",
                cls: "citybtn"
            } ]
        }, {
            id: 12,
            cls: "pview",
            count: 0,
            name: "新疆",
            city: [ {
                id: 1201,
                pid: 12,
                name: "乌鲁木齐",
                cls: "citybtn"
            }, {
                id: 1202,
                pid: 12,
                name: "克拉玛依",
                cls: "citybtn"
            }, {
                id: 1203,
                pid: 12,
                name: "石河子",
                cls: "citybtn"
            }, {
                id: 1204,
                pid: 12,
                name: "阿拉尔",
                cls: "citybtn"
            }, {
                id: 1205,
                pid: 12,
                name: "图木舒克",
                cls: "citybtn"
            }, {
                id: 1206,
                pid: 12,
                name: "五家渠",
                cls: "citybtn"
            }, {
                id: 1207,
                pid: 12,
                name: "北屯",
                cls: "citybtn"
            }, {
                id: 1208,
                pid: 12,
                name: "喀什",
                cls: "citybtn"
            }, {
                id: 1209,
                pid: 12,
                name: "阿克苏",
                cls: "citybtn"
            }, {
                id: 1210,
                pid: 12,
                name: "和田",
                cls: "citybtn"
            }, {
                id: 1211,
                pid: 12,
                name: "吐鲁番",
                cls: "citybtn"
            }, {
                id: 1212,
                pid: 12,
                name: "哈密",
                cls: "citybtn"
            }, {
                id: 1213,
                pid: 12,
                name: "阿图什",
                cls: "citybtn"
            }, {
                id: 1214,
                pid: 12,
                name: "博乐",
                cls: "citybtn"
            }, {
                id: 1215,
                pid: 12,
                name: "昌吉",
                cls: "citybtn"
            }, {
                id: 1216,
                pid: 12,
                name: "阜康",
                cls: "citybtn"
            }, {
                id: 1217,
                pid: 12,
                name: "米泉",
                cls: "citybtn"
            }, {
                id: 1218,
                pid: 12,
                name: "库尔勒",
                cls: "citybtn"
            }, {
                id: 1219,
                pid: 12,
                name: "伊宁",
                cls: "citybtn"
            }, {
                id: 1220,
                pid: 12,
                name: "奎屯",
                cls: "citybtn"
            }, {
                id: 1221,
                pid: 12,
                name: "塔城",
                cls: "citybtn"
            }, {
                id: 1222,
                pid: 12,
                name: "乌苏",
                cls: "citybtn"
            }, {
                id: 1223,
                pid: 12,
                name: "阿勒泰",
                cls: "citybtn"
            } ]
        }, {
            id: 13,
            cls: "pview",
            count: 0,
            name: "西藏",
            city: [ {
                id: 1301,
                pid: 13,
                name: "拉萨",
                cls: "citybtn"
            }, {
                id: 1302,
                pid: 13,
                name: "日喀则",
                cls: "citybtn"
            }, {
                id: 1303,
                pid: 13,
                name: "昌都",
                cls: "citybtn"
            }, {
                id: 1304,
                pid: 13,
                name: "林芝",
                cls: "citybtn"
            }, {
                id: 1305,
                pid: 13,
                name: "山南",
                cls: "citybtn"
            }, {
                id: 1306,
                pid: 13,
                name: "那曲",
                cls: "citybtn"
            }, {
                id: 1307,
                pid: 13,
                name: "阿里",
                cls: "citybtn"
            } ]
        }, {
            id: 14,
            cls: "pview",
            count: 0,
            name: "青海",
            city: [ {
                id: 1401,
                pid: 14,
                name: "西宁",
                cls: "citybtn"
            }, {
                id: 1402,
                pid: 14,
                name: "海东",
                cls: "citybtn"
            }, {
                id: 1403,
                pid: 14,
                name: "海北",
                cls: "citybtn"
            }, {
                id: 1404,
                pid: 14,
                name: "海西",
                cls: "citybtn"
            }, {
                id: 1405,
                pid: 14,
                name: "海南",
                cls: "citybtn"
            }, {
                id: 1406,
                pid: 14,
                name: "黄南",
                cls: "citybtn"
            }, {
                id: 1407,
                pid: 14,
                name: "果洛",
                cls: "citybtn"
            }, {
                id: 1408,
                pid: 14,
                name: "玉树",
                cls: "citybtn"
            }, {
                id: 1409,
                pid: 14,
                name: "德林哈",
                cls: "citybtn"
            }, {
                id: 1410,
                pid: 14,
                name: "格尔木",
                cls: "citybtn"
            }, {
                id: 1411,
                pid: 14,
                name: "海晏",
                cls: "citybtn"
            }, {
                id: 1412,
                pid: 14,
                name: "同仁",
                cls: "citybtn"
            }, {
                id: 1413,
                pid: 14,
                name: "共和",
                cls: "citybtn"
            }, {
                id: 1414,
                pid: 14,
                name: "玛沁",
                cls: "citybtn"
            } ]
        }, {
            id: 15,
            cls: "pview",
            count: 0,
            name: "甘肃",
            city: [ {
                id: 1501,
                pid: 15,
                name: "兰州",
                cls: "citybtn"
            }, {
                id: 1502,
                pid: 15,
                name: "嘉峪关",
                cls: "citybtn"
            }, {
                id: 1503,
                pid: 15,
                name: "金昌",
                cls: "citybtn"
            }, {
                id: 1504,
                pid: 15,
                name: "白银",
                cls: "citybtn"
            }, {
                id: 1505,
                pid: 15,
                name: "天水",
                cls: "citybtn"
            }, {
                id: 1506,
                pid: 15,
                name: "酒泉",
                cls: "citybtn"
            }, {
                id: 1507,
                pid: 15,
                name: "张掖",
                cls: "citybtn"
            }, {
                id: 1508,
                pid: 15,
                name: "武威",
                cls: "citybtn"
            }, {
                id: 1509,
                pid: 15,
                name: "庆阳",
                cls: "citybtn"
            }, {
                id: 1510,
                pid: 15,
                name: "平凉",
                cls: "citybtn"
            }, {
                id: 1511,
                pid: 15,
                name: "定西",
                cls: "citybtn"
            }, {
                id: 1512,
                pid: 15,
                name: "陇南",
                cls: "citybtn"
            }, {
                id: 1513,
                pid: 15,
                name: "玉门",
                cls: "citybtn"
            }, {
                id: 1514,
                pid: 15,
                name: "敦煌",
                cls: "citybtn"
            }, {
                id: 1515,
                pid: 15,
                name: "临夏",
                cls: "citybtn"
            }, {
                id: 1516,
                pid: 15,
                name: "合作",
                cls: "citybtn"
            } ]
        }, {
            id: 16,
            cls: "pview",
            count: 0,
            name: "宁夏",
            city: [ {
                id: 1601,
                pid: 16,
                name: "银川",
                cls: "citybtn"
            }, {
                id: 1602,
                pid: 16,
                name: "石嘴山",
                cls: "citybtn"
            }, {
                id: 1603,
                pid: 16,
                name: "吴忠",
                cls: "citybtn"
            }, {
                id: 1604,
                pid: 16,
                name: "中卫",
                cls: "citybtn"
            }, {
                id: 1605,
                pid: 16,
                name: "固原",
                cls: "citybtn"
            }, {
                id: 1606,
                pid: 16,
                name: "灵武",
                cls: "citybtn"
            }, {
                id: 1607,
                pid: 16,
                name: "青铜峡",
                cls: "citybtn"
            }, {
                id: 1608,
                pid: 16,
                name: "贺兰",
                cls: "citybtn"
            }, {
                id: 1609,
                pid: 16,
                name: "永宁",
                cls: "citybtn"
            }, {
                id: 1610,
                pid: 16,
                name: "平罗",
                cls: "citybtn"
            }, {
                id: 1611,
                pid: 16,
                name: "同心",
                cls: "citybtn"
            }, {
                id: 1612,
                pid: 16,
                name: "盐池",
                cls: "citybtn"
            }, {
                id: 1613,
                pid: 16,
                name: "西吉",
                cls: "citybtn"
            }, {
                id: 1614,
                pid: 16,
                name: "隆德",
                cls: "citybtn"
            }, {
                id: 1615,
                pid: 16,
                name: "泾源",
                cls: "citybtn"
            }, {
                id: 1616,
                pid: 16,
                name: "彭阳",
                cls: "citybtn"
            }, {
                id: 1617,
                pid: 16,
                name: "中宁",
                cls: "citybtn"
            }, {
                id: 1618,
                pid: 16,
                name: "海原",
                cls: "citybtn"
            } ]
        }, {
            id: 22,
            cls: "pview",
            count: 0,
            name: "福建",
            city: [ {
                id: 2201,
                pid: 22,
                name: "厦门",
                cls: "citybtn"
            }, {
                id: 2202,
                pid: 22,
                name: "福州",
                cls: "citybtn"
            }, {
                id: 2203,
                pid: 22,
                name: "南平",
                cls: "citybtn"
            }, {
                id: 2204,
                pid: 22,
                name: "三明",
                cls: "citybtn"
            }, {
                id: 2205,
                pid: 22,
                name: "莆田",
                cls: "citybtn"
            }, {
                id: 2206,
                pid: 22,
                name: "泉州",
                cls: "citybtn"
            }, {
                id: 2207,
                pid: 22,
                name: "漳州",
                cls: "citybtn"
            }, {
                id: 2208,
                pid: 22,
                name: "龙岩",
                cls: "citybtn"
            }, {
                id: 2209,
                pid: 22,
                name: "宁德",
                cls: "citybtn"
            }, {
                id: 2210,
                pid: 22,
                name: "福清",
                cls: "citybtn"
            }, {
                id: 2211,
                pid: 22,
                name: "长乐",
                cls: "citybtn"
            }, {
                id: 2212,
                pid: 22,
                name: "邵武",
                cls: "citybtn"
            }, {
                id: 2213,
                pid: 22,
                name: "武夷山",
                cls: "citybtn"
            }, {
                id: 2214,
                pid: 22,
                name: "建瓯",
                cls: "citybtn"
            }, {
                id: 2215,
                pid: 22,
                name: "建阳",
                cls: "citybtn"
            }, {
                id: 2216,
                pid: 22,
                name: "永安",
                cls: "citybtn"
            }, {
                id: 2217,
                pid: 22,
                name: "石狮",
                cls: "citybtn"
            }, {
                id: 2218,
                pid: 22,
                name: "晋江",
                cls: "citybtn"
            }, {
                id: 2219,
                pid: 22,
                name: "南安",
                cls: "citybtn"
            }, {
                id: 2220,
                pid: 22,
                name: "龙海",
                cls: "citybtn"
            }, {
                id: 2221,
                pid: 22,
                name: "漳平",
                cls: "citybtn"
            }, {
                id: 2222,
                pid: 22,
                name: "福安",
                cls: "citybtn"
            }, {
                id: 2223,
                pid: 22,
                name: "福鼎",
                cls: "citybtn"
            } ]
        }, {
            id: 23,
            cls: "pview",
            count: 0,
            name: "台湾",
            city: [ {
                id: 2301,
                pid: 23,
                name: "台北",
                cls: "citybtn"
            }, {
                id: 2302,
                pid: 23,
                name: "新北",
                cls: "citybtn"
            }, {
                id: 2303,
                pid: 23,
                name: "桃园",
                cls: "citybtn"
            }, {
                id: 2304,
                pid: 23,
                name: "台中",
                cls: "citybtn"
            }, {
                id: 2305,
                pid: 23,
                name: "台南",
                cls: "citybtn"
            }, {
                id: 2306,
                pid: 23,
                name: "高雄",
                cls: "citybtn"
            }, {
                id: 2307,
                pid: 23,
                name: "基隆",
                cls: "citybtn"
            }, {
                id: 2308,
                pid: 23,
                name: "新竹",
                cls: "citybtn"
            }, {
                id: 2309,
                pid: 23,
                name: "嘉义",
                cls: "citybtn"
            }, {
                id: 2310,
                pid: 23,
                name: "苗栗",
                cls: "citybtn"
            }, {
                id: 2311,
                pid: 23,
                name: "彰化",
                cls: "citybtn"
            }, {
                id: 2312,
                pid: 23,
                name: "云林",
                cls: "citybtn"
            }, {
                id: 2313,
                pid: 23,
                name: "屏东",
                cls: "citybtn"
            }, {
                id: 2314,
                pid: 23,
                name: "宜兰",
                cls: "citybtn"
            }, {
                id: 2315,
                pid: 23,
                name: "花莲",
                cls: "citybtn"
            }, {
                id: 2316,
                pid: 23,
                name: "台东",
                cls: "citybtn"
            }, {
                id: 2317,
                pid: 23,
                name: "澎湖",
                cls: "citybtn"
            } ]
        }, {
            id: 24,
            cls: "pview",
            count: 0,
            name: "广东",
            city: [ {
                id: 2401,
                pid: 24,
                name: "广州",
                cls: "citybtn"
            }, {
                id: 2402,
                pid: 24,
                name: "深圳",
                cls: "citybtn"
            }, {
                id: 2403,
                pid: 24,
                name: "清远",
                cls: "citybtn"
            }, {
                id: 2404,
                pid: 24,
                name: "韶关",
                cls: "citybtn"
            }, {
                id: 2405,
                pid: 24,
                name: "河源",
                cls: "citybtn"
            }, {
                id: 2406,
                pid: 24,
                name: "梅州",
                cls: "citybtn"
            }, {
                id: 2407,
                pid: 24,
                name: "潮州",
                cls: "citybtn"
            }, {
                id: 2408,
                pid: 24,
                name: "汕头",
                cls: "citybtn"
            }, {
                id: 2409,
                pid: 24,
                name: "揭阳",
                cls: "citybtn"
            }, {
                id: 2410,
                pid: 24,
                name: "汕尾",
                cls: "citybtn"
            }, {
                id: 2411,
                pid: 24,
                name: "惠州",
                cls: "citybtn"
            }, {
                id: 2412,
                pid: 24,
                name: "东莞",
                cls: "citybtn"
            }, {
                id: 2413,
                pid: 24,
                name: "珠海",
                cls: "citybtn"
            }, {
                id: 2414,
                pid: 24,
                name: "中山",
                cls: "citybtn"
            }, {
                id: 2415,
                pid: 24,
                name: "江门",
                cls: "citybtn"
            }, {
                id: 2416,
                pid: 24,
                name: "佛山",
                cls: "citybtn"
            }, {
                id: 2417,
                pid: 24,
                name: "肇庆",
                cls: "citybtn"
            }, {
                id: 2418,
                pid: 24,
                name: "云浮",
                cls: "citybtn"
            }, {
                id: 2419,
                pid: 24,
                name: "阳江",
                cls: "citybtn"
            }, {
                id: 2420,
                pid: 24,
                name: "茂名",
                cls: "citybtn"
            }, {
                id: 2421,
                pid: 24,
                name: "湛江",
                cls: "citybtn"
            }, {
                id: 2422,
                pid: 24,
                name: "从化",
                cls: "citybtn"
            }, {
                id: 2423,
                pid: 24,
                name: "增城",
                cls: "citybtn"
            }, {
                id: 2424,
                pid: 24,
                name: "英德",
                cls: "citybtn"
            }, {
                id: 2425,
                pid: 24,
                name: "连州",
                cls: "citybtn"
            }, {
                id: 2426,
                pid: 24,
                name: "乐昌",
                cls: "citybtn"
            }, {
                id: 2427,
                pid: 24,
                name: "南雄",
                cls: "citybtn"
            }, {
                id: 2428,
                pid: 24,
                name: "兴宁",
                cls: "citybtn"
            }, {
                id: 2429,
                pid: 24,
                name: "普宁",
                cls: "citybtn"
            }, {
                id: 2430,
                pid: 24,
                name: "陆丰",
                cls: "citybtn"
            }, {
                id: 2431,
                pid: 24,
                name: "恩平",
                cls: "citybtn"
            }, {
                id: 2432,
                pid: 24,
                name: "台山",
                cls: "citybtn"
            }, {
                id: 2433,
                pid: 24,
                name: "开平",
                cls: "citybtn"
            }, {
                id: 2434,
                pid: 24,
                name: "鹤山",
                cls: "citybtn"
            }, {
                id: 2435,
                pid: 24,
                name: "高要",
                cls: "citybtn"
            }, {
                id: 2436,
                pid: 24,
                name: "四会",
                cls: "citybtn"
            }, {
                id: 2437,
                pid: 24,
                name: "罗定",
                cls: "citybtn"
            }, {
                id: 2438,
                pid: 24,
                name: "阳春",
                cls: "citybtn"
            }, {
                id: 2439,
                pid: 24,
                name: "化州",
                cls: "citybtn"
            }, {
                id: 2440,
                pid: 24,
                name: "信宜",
                cls: "citybtn"
            }, {
                id: 2441,
                pid: 24,
                name: "高州",
                cls: "citybtn"
            }, {
                id: 2442,
                pid: 24,
                name: "吴川",
                cls: "citybtn"
            }, {
                id: 2443,
                pid: 24,
                name: "廉江",
                cls: "citybtn"
            }, {
                id: 2444,
                pid: 24,
                name: "雷州",
                cls: "citybtn"
            } ]
        }, {
            id: 25,
            cls: "pview",
            count: 0,
            name: "广西",
            city: [ {
                id: 2501,
                pid: 25,
                name: "南宁",
                cls: "citybtn"
            }, {
                id: 2502,
                pid: 25,
                name: "桂林",
                cls: "citybtn"
            }, {
                id: 2503,
                pid: 25,
                name: "柳州",
                cls: "citybtn"
            }, {
                id: 2504,
                pid: 25,
                name: "梧州",
                cls: "citybtn"
            }, {
                id: 2505,
                pid: 25,
                name: "贵港",
                cls: "citybtn"
            }, {
                id: 2506,
                pid: 25,
                name: "玉林",
                cls: "citybtn"
            }, {
                id: 2507,
                pid: 25,
                name: "钦州",
                cls: "citybtn"
            }, {
                id: 2508,
                pid: 25,
                name: "北海",
                cls: "citybtn"
            }, {
                id: 2509,
                pid: 25,
                name: "防城港",
                cls: "citybtn"
            }, {
                id: 2510,
                pid: 25,
                name: "崇左",
                cls: "citybtn"
            }, {
                id: 2511,
                pid: 25,
                name: "百色",
                cls: "citybtn"
            }, {
                id: 2512,
                pid: 25,
                name: "河池",
                cls: "citybtn"
            }, {
                id: 2513,
                pid: 25,
                name: "来宾",
                cls: "citybtn"
            }, {
                id: 2514,
                pid: 25,
                name: "贺州",
                cls: "citybtn"
            }, {
                id: 2515,
                pid: 25,
                name: "岑溪",
                cls: "citybtn"
            }, {
                id: 2516,
                pid: 25,
                name: "桂平",
                cls: "citybtn"
            }, {
                id: 2517,
                pid: 25,
                name: "北流",
                cls: "citybtn"
            }, {
                id: 2518,
                pid: 25,
                name: "东兴",
                cls: "citybtn"
            }, {
                id: 2519,
                pid: 25,
                name: "凭祥",
                cls: "citybtn"
            }, {
                id: 2520,
                pid: 25,
                name: "宜州",
                cls: "citybtn"
            }, {
                id: 2521,
                pid: 25,
                name: "合山",
                cls: "citybtn"
            } ]
        }, {
            id: 28,
            cls: "pview",
            count: 0,
            name: "贵州",
            city: [ {
                id: 2801,
                pid: 28,
                name: "贵阳",
                cls: "citybtn"
            }, {
                id: 2802,
                pid: 28,
                name: "六盘水",
                cls: "citybtn"
            }, {
                id: 2803,
                pid: 28,
                name: "遵义",
                cls: "citybtn"
            }, {
                id: 2804,
                pid: 28,
                name: "安顺",
                cls: "citybtn"
            }, {
                id: 2805,
                pid: 28,
                name: "毕节",
                cls: "citybtn"
            }, {
                id: 2806,
                pid: 28,
                name: "铜仁",
                cls: "citybtn"
            }, {
                id: 2807,
                pid: 28,
                name: "清镇",
                cls: "citybtn"
            }, {
                id: 2808,
                pid: 28,
                name: "赤水",
                cls: "citybtn"
            }, {
                id: 2809,
                pid: 28,
                name: "仁怀",
                cls: "citybtn"
            }, {
                id: 2810,
                pid: 28,
                name: "凯里",
                cls: "citybtn"
            }, {
                id: 2811,
                pid: 28,
                name: "都匀",
                cls: "citybtn"
            }, {
                id: 2812,
                pid: 28,
                name: "兴义",
                cls: "citybtn"
            }, {
                id: 2813,
                pid: 28,
                name: "福泉",
                cls: "citybtn"
            }, {
                id: 2814,
                pid: 28,
                name: "盘州",
                cls: "citybtn"
            } ]
        } ];
    }
};